services:
  - name: NFT MarketPlace
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        fromEnv: DB_HOST
      - key: DB_USER
        fromEnv: DB_USER
      - key: DB_PASSWORD
        fromEnv: DB_PASSWORD
      - key: DB_DATABASE
        fromEnv: DB_DATABASE
